---
title: serp.gr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: adsinf2@yahoo.com
description: Κατασκευή ιστοσελίδων, Προώθηση ιστοσελίδων, Ανάλυση ανταγωνισμού, Υπηρεσίες δόμησης συνδέσμων (link building), Συγγραφή  κειμένων για ιστοσελίδες (copywriting), Αύξηση επισκεψιμότητας και branding για να ξεχωρίσετε στο Διαδίκτυο.
baseurl: ''
url: 'https://seoblog7982.github.io'
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
encoding: UTF-8
