---
title: seoblog7
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: adsinf2@yahoo.com
description: Предлагани услуги: Изработка на сайт, SEO оптимизация, изработка на мобилни приложения за Android, графичен дизайн, копирайтинг, content marketing, анализ и консултации за бизнес сайтове.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
encoding: UTF-8
