---
title: seoblog7
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: adsinf2@yahoo.com
description: Изработка на сайт, SEO оптимизация за google, линк билдинг, графичен дизайн, копирайтинг, content marketing, анализ, одит и консултации за бизнес сайтове.
baseurl: ''
url: 'https://seoblog7982.github.io'
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
encoding: UTF-8
